---
title: "Reading Data from the Web"
output: github_document
---
this is the repository for data wrangling 2 part of P8105

```{r setup}
library(tidyverse)
library(rvest)
library(httr)
```

## Extracting Tables
read html from the url
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

Get the pieces I actuslly need
```{r}
drug_use_html |>
  html_table() |>
  first()
```


```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1) 

table_marj
```

## Learning Assessment
Create data frame that contains cost of living table for New York
```{r}
nyc_cost_df =
  read_html ("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |>
  html_table(header=TRUE) |>
  first()
```

## CSS Selectors
```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"
swm_html = read_html(swm_url)
```

```{r}
title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)
```

Extract the book titles, stars, and prices.
```{r}
url = "http://books.toscrape.com"

books_html = read_html(url)

books_titles = 
  books_html |>
  html_elements("h3") |>
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price
)
```

